# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b951f4b55240e4505c7eadbbf85e14701baabe8fe8c378779b9832e91b3c962b9f5134bdf33469fe58d4e5258e8faf74e5ebcafdd2ea5a591436181a5e73a7b

test:
  secret_key_base: 88ec90a299cbe8b4694952abb44b3b74c057d2ef78cf9e6745d605058b91ec340317018a44ef6038d82ca8e9c668e73c9c9ba6a499e6afbf077b6808bb10bbd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
